name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: student-sandbox-project
  REGION: europe-west1
  APP_NAME: musicglen
  REGISTRY_NAME: gcr.io
  SERVICE_ACCOUNT_EMAIL: ivonne-app-sa@student-sandbox-project.iam.gserviceaccount.com

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker gcr.io

      - name: Build and tag the docker image
        run: |-
          docker build -t $REGISTRY_NAME/$PROJECT_ID/$APP_NAME:latest .

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg DB_HOST=${{ secrets.DB_HOST_SUPERBASE }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT_SUPERBASE }} \
            --build-arg DB_DATABASE=${{ secrets.DB_DATABASE_SUPERBASE }} \
            --build-arg DB_USERNAME=${{ secrets.DB_USER_SUPERBASE }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD_SUPERBASE }} \
            --build-arg DB_TYPE=${{ secrets.DB_TYPE }} \
            --build-arg PORT=${{ secrets.PORT }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-glen:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-glen:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: node-glen
          image: gcr.io/${{ secrets.GCP_PROJECT_ID}}/node-glen:latest
          region: europe-west1
          platform: managed
          allow-authenticated: true


      - name: Allow unauthenticated access
        run: |
          gcloud run services add-iam-policy-binding node-glen \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=europe-west1 \
            --platform=managed
        