name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install
          
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'gcr.io'

      - name: Build and Push Docker Image
        run: |
          docker build \
            --build-arg DB_HOST_SUPERBASE=${{ secrets.DB_HOST_SUPERBASE || "localhost" }} \
            --build-arg DB_PORT_SUPERBASE=${{ secrets.DB_PORT_SUPERBASE || "5432" }} \
            --build-arg DB_DATABASE_SUPERBASE=${{ secrets.DB_DATABASE_SUPERBASE || "database" }} \
            --build-arg DB_USER_SUPERBASE=${{ secrets.DB_USER_SUPERBASE || "user" }} \
            --build-arg DB_PASSWORD_SUPERBASE=${{ secrets.DB_PASSWORD_SUPERBASE || "password" }} \
            --build-arg DB_TYPE=${{ secrets.DB_TYPE || "postgres" }} \
            --build-arg PORT=${{ secrets.PORT || "8080" }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-glen:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-glen:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: node-glen
          image: gcr.io/${{ secrets.GCP_PROJECT_ID}}/node-glen
          region: ${{ secrets.GCP_REGION }}
          platform: managed
          allow-authenticated: true


      - name: Allow unauthenticated access
        run: |
          gcloud run services add-iam-policy-binding node-glen \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=europe-west1 \
            --platform=managed
        
        