name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: student-sandbox-project
  REGION: europe-west1
  APP_NAME: music-app-glen
  REGISTRY_NAME: eu.gcr.io/student-sandbox-project/music-app-glen
  SERVICE_ACCOUNT_EMAIL: githubaction@student-sandbox-project.iam.gserviceaccount.com

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDvK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        run: |-
          docker build --platform linux/amd64 -t $REGISTRY_NAME/$PROJECT_ID/$APP_NAME:$GITHUB_SHA .

      - name: Push the image to the Google Artifact Registry (GAR)
        run: |-
          docker push $REGISTRY_NAME/$PROJECT_ID/$APP_NAME:$GITHUB_SHA

      - name: Deploy
        run: |-
          gcloud run deploy $APP_NAME \
          --region $REGION \
          --image $REGISTRY_NAME/$PROJECT_ID/$APP_NAME:$GITHUB_SHA \
          --platform "managed" \
          --service-account $SERVICE_ACCOUNT_EMAIL \
          --port 8080 \
          --quiet