name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: music-app-glen
          platforms: linux/amd64
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: music-app-glen
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-app-glen
          region: europe-west1
          platform: managed
          allow-unauthenticated: true