name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_REPOSITORY_NAME }}
          docker build . -t $IMAGE_NAME:$GITHUB_RUN_ID
          docker push $IMAGE_NAME:$GITHUB_RUN_ID

      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_REPOSITORY_NAME }}
          gcloud run deploy ${{ secrets.GCP_INSTANCE_ID }} \
            --image $IMAGE_NAME:$GITHUB_RUN_ID \
            --allow-unauthenticated \
            --port ${{ secrets.GCP_APP_PORT }} \
            --region europe-west1 \
            --platform managed